# Generated by Django 3.1.3 on 2020-12-19 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntroImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intimg', models.ImageField(upload_to='myimg/intro')),
            ],
        ),
        migrations.CreateModel(
            name='PortProd1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hname', models.CharField(max_length=50)),
                ('pname', models.CharField(max_length=50)),
                ('imge', models.ImageField(upload_to='webimg/prod1')),
            ],
        ),
        migrations.CreateModel(
            name='PortProd2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hname', models.CharField(max_length=50)),
                ('pname', models.CharField(max_length=50)),
                ('imge', models.ImageField(upload_to='webimg/prod2')),
            ],
        ),
        migrations.CreateModel(
            name='PortProd3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hname', models.CharField(max_length=50)),
                ('pname', models.CharField(max_length=50)),
                ('imge', models.ImageField(upload_to='webimg/prod3')),
            ],
        ),
        migrations.CreateModel(
            name='Servi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imge', models.ImageField(upload_to='webimg/serimg')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=200)),
            ],
        ),
    ]
